# Generated by Django 2.1 on 2020-06-29 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_id', models.IntegerField(max_length=9)),
                ('year', models.IntegerField(default='2020')),
                ('tran_type', models.CharField(max_length=10)),
                ('transaction_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
