# Generated by Django 2.1 on 2020-06-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savtrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_savings',
            name='bill',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_savings',
            name='transaction_amt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='my_savings',
            name='sa_id',
            field=models.IntegerField(),
        ),
    ]
