# Generated by Django 2.1 on 2020-07-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savtrack', '0003_auto_20200713_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_savings',
            name='sa_id',
            field=models.IntegerField(null=True),
        ),
    ]
