# Generated by Django 2.1 on 2020-07-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savtrack', '0008_auto_20200713_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_savings',
            name='transaction_amt',
            field=models.IntegerField(null=True),
        ),
    ]
